import * as types from './types';
import { FirebaseApi } from '../firebase/firebase';

export default new FirebaseApi('categoriesQuestions', {
  LOAD_REQUEST: types.LOAD_CATEGORIES_QUESTIONS_REQUEST,
  LOAD_SUCCESS: types.LOAD_CATEGORIES_QUESTIONS_SUCCESS,
  UNLOAD_SUCCESS: types.UNLOAD_CATEGORIES_QUESTIONS_SUCCESS,
  SET_ACTIVE: types.SET_ACTIVE_CATEGORIES_QUESTIONS,
  RESET_ACTIVE: types.RESET_ACTIVE_CATEGORIES_QUESTIONS,
  CREATE: types.CREATE_CATEGORIES_QUESTIONS,
  SET_MATCHING: types.SET_MATCHING_CATEGORIES_QUESTIONS,
}, 'name');
