import { ARCHIVED_ACTION_PREFIX } from '../constants/general';

export const LOAD_DIRECTS_REQUEST = 'LOAD_DIRECTS_REQUEST';
export const LOAD_DIRECTS_SUCCESS = 'LOAD_DIRECTS_SUCCESS';
export const UNLOAD_DIRECTS_SUCCESS = 'UNLOAD_DIRECTS_SUCCESS';
export const CREATE_DIRECT = 'CREATE_DIRECT';
export const SET_ACTIVE_DIRECT = 'SET_ACTIVE_DIRECT';
export const RESET_ACTIVE_DIRECT = 'RESET_ACTIVE_DIRECT';
export const SET_MATCHING_DIRECTS = 'SET_MATCHING_DIRECTS';
export const SET_DIRECTS_SORT_BY = 'SET_DIRECTS_SORT_BY';

export const ARCHIVED_LOAD_DIRECTS_REQUEST = `${ARCHIVED_ACTION_PREFIX}LOAD_DIRECTS_REQUEST`;
export const ARCHIVED_LOAD_DIRECTS_SUCCESS = `${ARCHIVED_ACTION_PREFIX}LOAD_DIRECTS_SUCCESS`;
export const ARCHIVED_UNLOAD_DIRECTS_SUCCESS = `${ARCHIVED_ACTION_PREFIX}UNLOAD_DIRECTS_SUCCESS`;
export const ARCHIVED_CREATE_DIRECT = `${ARCHIVED_ACTION_PREFIX}CREATE_DIRECT`;
export const ARCHIVED_SET_ACTIVE_DIRECT = `${ARCHIVED_ACTION_PREFIX}SET_ACTIVE_DIRECT`;
export const ARCHIVED_RESET_ACTIVE_DIRECT = `${ARCHIVED_ACTION_PREFIX}RESET_ACTIVE_DIRECT`;
export const ARCHIVED_SET_MATCHING_DIRECTS = `${ARCHIVED_ACTION_PREFIX}SET_MATCHING_DIRECTS`;
export const ARCHIVED_SET_DIRECTS_SORT_BY = `${ARCHIVED_ACTION_PREFIX}SET_DIRECTS_SORT_BY`;

export const LOAD_MEETINGS_REQUEST = 'LOAD_MEETINGS_REQUEST';
export const LOAD_MEETINGS_SUCCESS = 'LOAD_MEETINGS_SUCCESS';
export const UNLOAD_MEETINGS_SUCCESS = 'UNLOAD_MEETINGS_SUCCESS';
export const CREATE_MEETING = 'CREATE_MEETING';
export const SET_ACTIVE_MEETING = 'SET_ACTIVE_MEETING';
export const RESET_ACTIVE_MEETING = 'RESET_ACTIVE_MEETING';
export const SET_MATCHING_MEETINGS = 'SET_MATCHING_MEETINGS';

export const ARCHIVED_LOAD_MEETINGS_REQUEST = `${ARCHIVED_ACTION_PREFIX}LOAD_MEETINGS_REQUEST`;
export const ARCHIVED_LOAD_MEETINGS_SUCCESS = `${ARCHIVED_ACTION_PREFIX}LOAD_MEETINGS_SUCCESS`;
export const ARCHIVED_UNLOAD_MEETINGS_SUCCESS = `${ARCHIVED_ACTION_PREFIX}UNLOAD_MEETINGS_SUCCESS`;
export const ARCHIVED_CREATE_MEETING = `${ARCHIVED_ACTION_PREFIX}CREATE_MEETING`;
export const ARCHIVED_SET_ACTIVE_MEETING = `${ARCHIVED_ACTION_PREFIX}SET_ACTIVE_MEETING`;
export const ARCHIVED_RESET_ACTIVE_MEETING = `${ARCHIVED_ACTION_PREFIX}RESET_ACTIVE_MEETING`;
export const ARCHIVED_SET_MATCHING_MEETINGS = `${ARCHIVED_ACTION_PREFIX}SET_MATCHING_MEETINGS`;

export const LOAD_FOLLOW_UPS_REQUEST = 'LOAD_FOLLOW_UPS_REQUEST';
export const LOAD_FOLLOW_UPS_SUCCESS = 'LOAD_FOLLOW_UPS_SUCCESS';
export const UNLOAD_FOLLOW_UPS_SUCCESS = 'UNLOAD_FOLLOW_UPS_SUCCESS';
export const CREATE_FOLLOW_UP = 'CREATE_FOLLOW_UP';
export const SET_ACTIVE_FOLLOW_UP = 'SET_ACTIVE_FOLLOW_UP';
export const RESET_ACTIVE_FOLLOW_UP = 'RESET_ACTIVE_FOLLOW_UP';
export const SET_MATCHING_FOLLOW_UPS = 'SET_MATCHING_FOLLOW_UPS';

export const ARCHIVED_LOAD_FOLLOW_UPS_REQUEST = `${ARCHIVED_ACTION_PREFIX}LOAD_FOLLOW_UPS_REQUEST`;
export const ARCHIVED_LOAD_FOLLOW_UPS_SUCCESS = `${ARCHIVED_ACTION_PREFIX}LOAD_FOLLOW_UPS_SUCCESS`;
export const ARCHIVED_UNLOAD_FOLLOW_UPS_SUCCESS = `${ARCHIVED_ACTION_PREFIX}UNLOAD_FOLLOW_UPS_SUCCESS`;
export const ARCHIVED_CREATE_FOLLOW_UP = `${ARCHIVED_ACTION_PREFIX}CREATE_FOLLOW_UP`;
export const ARCHIVED_SET_ACTIVE_FOLLOW_UP = `${ARCHIVED_ACTION_PREFIX}SET_ACTIVE_FOLLOW_UP`;
export const ARCHIVED_RESET_ACTIVE_FOLLOW_UP = `${ARCHIVED_ACTION_PREFIX}RESET_ACTIVE_FOLLOW_UP`;
export const ARCHIVED_SET_MATCHING_FOLLOW_UPS = `${ARCHIVED_ACTION_PREFIX}SET_MATCHING_FOLLOW_UPS`;

export const LOAD_TEAMS_REQUEST = 'LOAD_TEAMS_REQUEST';
export const LOAD_TEAMS_SUCCESS = 'LOAD_TEAMS_SUCCESS';
export const UNLOAD_TEAMS_SUCCESS = 'UNLOAD_TEAMS_SUCCESS';
export const CREATE_TEAM = 'CREATE_TEAM';
export const SET_ACTIVE_TEAM = 'SET_ACTIVE_TEAM';
export const RESET_ACTIVE_TEAM = 'RESET_ACTIVE_TEAM';
export const SET_MATCHING_TEAMS = 'SET_MATCHING_TEAMS';

export const AUTH_LOGIN = 'AUTH_LOGIN';
export const AUTH_LOGGED_IN = 'AUTH_LOGGED_IN';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';
export const AUTH_ANONYMOUS = 'AUTH_ANONYMOUS';
export const AUTH_OPEN = 'AUTH_OPEN';
export const AUTH_AWAITING_RESPONSE = 'AUTH_AWAITING_RESPONSE';
export const AUTH_ERROR = 'AUTH_ERROR';

export const LOAD_QUESTIONS_REQUEST = 'LOAD_QUESTIONS_REQUEST';
export const LOAD_QUESTIONS_SUCCESS = 'LOAD_QUESTIONS_SUCCESS';
export const UNLOAD_QUESTIONS_SUCCESS = 'UNLOAD_QUESTIONS_SUCCESS';
export const CREATE_QUESTIONS = 'CREATE_QUESTIONS';
export const SET_ACTIVE_QUESTIONS = 'SET_ACTIVE_QUESTIONS';
export const RESET_ACTIVE_QUESTIONS = 'RESET_ACTIVE_QUESTIONS';
export const SET_MATCHING_QUESTIONS = 'SET_MATCHING_QUESTIONS';

export const FLASH_NOTICE = 'FLASH_NOTICE';
export const FLASH_INFO = 'FLASH_INFO';
export const FLASH_ERROR = 'FLASH_ERROR';

export const HEADER_SET_TEXT = 'HEADER_SET_TEXT';
export const HEADER_RESET = 'HEADER_RESET';
