export const LOAD_DIRECTS_SUCCESS = 'LOAD_DIRECTS_SUCCESS';
export const UNLOAD_DIRECTS_SUCCESS = 'UNLOAD_DIRECTS_SUCCESS';
export const CREATE_DIRECT = 'CREATE_DIRECT';
export const SET_ACTIVE_DIRECT = 'SET_ACTIVE_DIRECT';
export const RESET_ACTIVE_DIRECT = 'RESET_ACTIVE_DIRECT';

export const LOAD_MEETINGS_SUCCESS = 'LOAD_MEETINGS_SUCCESS';
export const UNLOAD_MEETINGS_SUCCESS = 'UNLOAD_MEETINGS_SUCCESS';
export const CREATE_MEETING = 'CREATE_MEETING';
export const SET_ACTIVE_MEETING = 'SET_ACTIVE_MEETING';
export const RESET_ACTIVE_MEETING = 'RESET_ACTIVE_MEETING';

export const AUTH_LOGIN = 'AUTH_LOGIN';
export const AUTH_LOGGED_IN = 'AUTH_LOGGED_IN';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';
export const AUTH_ANONYMOUS = 'AUTH_ANONYMOUS';
export const AUTH_OPEN = 'AUTH_OPEN';
export const AUTH_AWAITING_RESPONSE = 'AUTH_AWAITING_RESPONSE';
export const AUTH_ERROR = 'AUTH_ERROR';

export const FLASH_NOTICE = 'FLASH_NOTICE';
export const FLASH_INFO = 'FLASH_INFO';
export const FLASH_ERROR = 'FLASH_ERROR';

export const HEADER_SET_TEXT = 'HEADER_SET_TEXT';
export const HEADER_RESET = 'HEADER_RESET';
